name: build-run-upload

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build packages
        run: sudo apt-get install -y lcov cmake g++

      - name: Configure CMake flags and build executables (Allow failures)
        run: |
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S . -B build/
          cmake --build build/ --clean-first --target all test_coverage || true
        continue-on-error: true

      - name: Generate Coverage Report
        run: lcov --capture --directory build --output-file build/test_coverage.info || true
        continue-on-error: true

      - name: Check coverage report file
        run: ls -l build/test_coverage.info

      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{github.workspace}}/build/test_coverage.info
          fail_ci_if_error: false
          verbose: true
